image:
  repository: bh7cw/notifier-webapp
  name: notifier-webapp

imagePullSecrets: docker-hub
port: 8080

readinessProbe:
  path: /actuator/health
  initialDelaySeconds: 45
  periodSeconds: 5

livenessProbe:
  path: /v1/helloworld
  initialDelaySeconds: 120
  periodSeconds: 10

resources:
  memory: 256Mi
  cpu: 500m

hpa:
  minReplicas: 1
  maxReplicas: 2
  target:
    averageUtilization: 5

mysql:
  spring: prod
  main:
    dbHost: 35.196.0.248
    dbPort: 3306
    dbName: csye7125
    dbUsername: root
    dbPassword: MysqlPwd123
  notifier:
    dbHost: 34.74.172.135
    dbPort: 3306
    dbName: notifier
    dbUsername: root
    dbPassword: MysqlPwd123

elasticsearch:
  esHost: elasticsearch-master.default
  esPort: 9200

deployment:
  replicas: 2
  progressDeadlineSeconds: 600
  minReadySeconds: 30
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0
  type: RollingUpdate
  # Monitoring: Adjust Prometheus configuration
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "8080"
  svc:
    port: 80

aws:
  accessKeyId: AKIA5EQQLUEDJMT3PDGV
  secretKey: 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

notifier:
  scanPeriod: 300000  # 1000 * 60 * 5 = 300000 milis = 5 mins