apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-secret
type: Opaque
data:
  MYSQL_DB_USERNAME: {{ .Values.mysql.main.dbUsername | b64enc | quote }}
  MYSQL_DB_PASSWORD: {{ .Values.mysql.main.dbPassword | b64enc | quote }}
  NOTIFIER_MYSQL_DB_USERNAME: {{ .Values.mysql.notifier.dbUsername | b64enc | quote }}
  NOTIFIER_MYSQL_DB_PASSWORD: {{ .Values.mysql.notifier.dbPassword | b64enc | quote }}
  AWS_ACCESS_KEY_ID: {{ .Values.aws.accessKeyId | b64enc | quote }}
  AWS_SECRET_KEY: {{ .Values.aws.secretKey | b64enc | quote }}